// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm8jNYKgL6C28ytQ_NtJCS2Tw-tGOZbeo',
    appId: '1:210286845891:web:6a1a23c07e3d74bae66776',
    messagingSenderId: '210286845891',
    projectId: 'bagator-abcd2',
    authDomain: 'bagator-abcd2.firebaseapp.com',
    storageBucket: 'bagator-abcd2.appspot.com',
    measurementId: 'G-DP301S7PKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGHvJ-HmeTr3L5nM9VCODZmvc8AAImoc',
    appId: '1:210286845891:android:d5431adc0010158ae66776',
    messagingSenderId: '210286845891',
    projectId: 'bagator-abcd2',
    storageBucket: 'bagator-abcd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-2hS2iH7dR3UWud5VrJY_SIR1VSuRY04',
    appId: '1:210286845891:ios:d4bf4b2e29ddc5c6e66776',
    messagingSenderId: '210286845891',
    projectId: 'bagator-abcd2',
    storageBucket: 'bagator-abcd2.appspot.com',
    iosClientId: '210286845891-ebsf35jhevrasonm1mlf463ljva56t6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.bagator',
  );
}
